=== Shattered-P/Classes/LPROG/src/PL_6/PL6_5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="sistema" type="TSistema"/>
    <xsd:complexType name="TSistema">
        <xsd:sequence>
            <xsd:element name="computador" type="TComputador" />
            <xsd:element name="componentes" type="TComponentes" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TComputador">
        <xsd:sequence>
            <xsd:element name="componente" type="PComponente" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="descricao" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="PComponente">
        <xsd:sequence>
            <xsd:element name="componente"></xsd:element>
        </xsd:sequence>
        <xsd:key name="id">
            <xsd:selector xpath="./TComponentes/"/>
        </xsd:key>
    </xsd:complexType>
    <xsd:complexType name="TComponentes">
        <xsd:sequence>
            <xsd:complexType name="PCComponente">
                <xsd:element name="item" type="Titem"></xsd:element>
                <xsd:element name= "modelo" type="Tmodelo"></xsd:element>
                <xsd:element name="preço" type="Tpreço"></xsd:element>
            </xsd:complexType>
        </xsd:sequence>
        <xsd:attribute name="codigo"></xsd:attribute>
    </xsd:complexType>
    <xsd:simpleType name="Titem">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="Motherboard|Video Card|Sound Card|Monitor|CPU|HDD|DVD"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Tmodelo">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z|a-z|\s|-|0-9]{32}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Tpreço">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]*.[0-9][0-9]"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Shattered-P/Classes/LPROG/src/PL_6/PL6_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<sistema 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="PL6_5.xsd">
    <computador descricao="Meu computador">
        <componente id="R10D"/> <!--atributo id corresponde a código do componente -->
        <componente id="RA01"/>
        <componente id="RF0B"/>
        <componente id="RAE1"/>
    </computador>
    <componentes>
        <componente codigo ="RA01">
            <item>Motherboard</item> <!-- Só são possíveis os valores: Motherboard,
Video Card, Sound Card, Monitor, CPU, HDD, DVD -->
            <modelo>P3B-F</modelo> <!-- máx 32 letras -->
            <preco>100.00</preco> <!-- padrão monetário com dois dígitos após o
ponto -->
        </componente>
        <componente codigo ="RAE1">
            <item>Monitor</item>
            <modelo>995E</modelo>
            <preco>200.00</preco>
        </componente>
        <componente codigo ="RAF2">
            <item>Monitor</item>
            <modelo>L198H</modelo>
            <preco>120.00</preco>
        </componente>
        <componente codigo ="R10D">
            <item>Sound Card</item>
            <modelo>Sound Blaster Live</modelo>
            <preco>80.00</preco>
        </componente>
        <componente codigo ="RF0B">
            <item>Video Card</item>
            <modelo>All-in-Wonder Pro</modelo>
            <preco>120.00</preco>
        </componente>
        <componente codigo ="RA02">
            <item>Motherboard</item>
            <modelo>A8G-2</modelo>
            <preco>350.00</preco>
        </componente>
    </componentes>
</sistema>
